services:
  app:
    build: .
    container_name: dobble-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dobble
      SPRING_DATASOURCE_USERNAME: dobble
      SPRING_DATASOURCE_PASSWORD: dobble
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - dobble-network

  db:
    image: postgres:15
    container_name: dobble-postgres
    restart: always
    environment:
      POSTGRES_DB: dobble
      POSTGRES_USER: dobble
      POSTGRES_PASSWORD: dobble
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./initCards.sql:/docker-entrypoint-initdb.d/initCards.sql
    networks:
      - dobble-network

volumes:
  pgdata:

networks:
  dobble-network:
